import {
  Book,
  BookOpen,
  Box,
  Bike,
  Brain,
  Briefcase,
  CalendarDays,
  Camera,
  Code,
  Coffee,
  Dumbbell,
  Flower2,
  Gamepad2,
  GraduationCap,
  Heart,
  Headphones,
  House,
  Landmark,
  Languages,
  Lightbulb,
  Monitor,
  Music,
  Palette,
  PawPrint,
  Pen,
  Plane,
  Rocket,
  ShoppingBag,
  Smartphone,
  TreePine,
  Trophy,
  Utensils,
  Video,
  WalletCards,
  Wrench,
  Users,
  type LucideIcon,
} from 'lucide-react'

/** The icon set a direction can pick from. `directions.icon` stores one of these ids. */
export const DIRECTION_ICONS: Record<string, LucideIcon> = {
  briefcase: Briefcase,
  rocket: Rocket,
  video: Video,
  languages: Languages,
  book: Book,
  code: Code,
  pen: Pen,
  dumbbell: Dumbbell,
  music: Music,
  camera: Camera,
  heart: Heart,
  brain: Brain,
  'graduation-cap': GraduationCap,
  'book-open': BookOpen,
  palette: Palette,
  lightbulb: Lightbulb,
  monitor: Monitor,
  smartphone: Smartphone,
  headphones: Headphones,
  coffee: Coffee,
  gamepad: Gamepad2,
  house: House,
  users: Users,
  plane: Plane,
  wallet: WalletCards,
  landmark: Landmark,
  utensils: Utensils,
  shopping: ShoppingBag,
  bike: Bike,
  trophy: Trophy,
  nature: TreePine,
  flower: Flower2,
  pet: PawPrint,
  tools: Wrench,
  calendar: CalendarDays,
  box: Box,
}

export const DIRECTION_ICON_IDS = Object.keys(DIRECTION_ICONS)

/** Unknown or legacy icon ids fall back to the neutral box. */
export function iconFor(id: string): LucideIcon {
  return DIRECTION_ICONS[id] ?? Box
}
